Mise a jours des informations de liaison
Mineweb/docs.mineweb.org pull request #6
Opened 2018-08-05 18:38 UTC by KuroSenseii

2018-08-05 18:40 UTC, Eywek requested changes

2018-08-05 18:40 UTC, Eywek commented on index.html
> +  - Par Rcon : <em>connexion à un serveur lié avec le Rcon. Pour la liaison d'un serveur Bungee, utilisé le <a href="https://www.spigotmc.org/resources/bungeecord-rcon.5817/">Plugin Bungeecord RCON</
Ça serait bien d’éviter les fautes d’orthographes sur la doc ;)

2018-08-05 19:15 UTC, Suertzz commented on index.html
> +  - Par Rcon : <em>connexion à un serveur lié avec le Rcon. Pour la liaison d'un serveur Bungee, utilisé le <a href="https://www.spigotmc.org/resources/bungeecord-rcon.5817/">Plugin Bungeecord RCON</
Corrige si t'es pas content

2018-08-27 14:02 UTC, Eywek approved these changes

2018-08-27 14:02 UTC, merged