Update Documentation
Mineweb/docs.mineweb.org pull request #8
Opened 2018-11-17 18:56 UTC by nivcoo

2018-11-22 10:06 UTC, Eywek requested changes
Et pourquoi avoir supprimé le fichier de compatibilité ?

2018-11-22 10:06 UTC, Eywek commented on source/index.html.md
> +
C'est plus à mettre dans aide et problèmes fréquents (https://github.com/MineWeb/docs.mineweb.org/blob/master/source/includes/_setup.md#aide-externe-et-probl%C3%A8mes-fr%C3%A9quents) non ?

2018-11-22 10:06 UTC, Eywek commented on source/index.html.md
> +*   Falcutatif - Php-xml
Pour ?

2018-11-22 10:06 UTC, Eywek commented on source/index.html.md
> +*   Version PHP supérieure ou égale à 5.6 et inférieure à 7.2 (php 7.2 ne pourra pas être compatible avec le CMS)
Plus valable avec ta PR du coup

2018-11-22 10:06 UTC, Eywek commented on source/index.html.md
> +*   .htaccess présent à la racine du CMS
Y'a les deux, et avoir le htaccess à la racine c'est pas vraiment un pré-requis, plus une aide si jamais ça fonctionne pas

2018-11-22 10:15 UTC, nivcoo commented on source/index.html.md
> +*   Falcutatif - Php-xml
Pour certain thème

2018-11-22 10:19 UTC, Eywek commented on source/index.html.md
> +*   Falcutatif - Php-xml
Des thèmes ont besoin de parse du XML ? C'est quoi cette merde

2018-11-22 10:20 UTC, nivcoo commented on source/index.html.md
> +*   Falcutatif - Php-xml
Oui après peut être le mieux c’est de changer ce système directement sur les thèmes qui ont ça non ?

2018-11-22 15:48 UTC, nivcoo commented
Voila

2019-04-20 15:32 UTC, Eywek approved these changes

2019-04-20 15:32 UTC, merged